# Generated by Django 4.2.15 on 2024-08-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_listname_elementoflist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listname',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
