# Generated by Django 4.2.15 on 2024-08-20 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_pub_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_remove_following_user_following_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='want_to_watch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
