# Generated by Django 4.2.15 on 2024-08-21 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_want_to_watch_count_profile_watched_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedmovie',
            name='watch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
