# Generated by Django 4.2.15 on 2024-08-23 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_watchedmovie_watch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedmovie',
            name='like_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wanttowatchmovie',
            name='want_to_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
