# Generated by Django 4.2.15 on 2024-08-23 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_likedmovie_like_date_wanttowatchmovie_want_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoflist',
            name='element_add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
