# Generated by Django 4.2.15 on 2024-08-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_movie_likes'),
        ('users', '0011_remove_profile_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='want_to_watch_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watched_count',
        ),
        migrations.AlterField(
            model_name='likedmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='movies.movie'),
        ),
    ]
