# Generated by Django 4.2.15 on 2024-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='poster.jpg', upload_to='movie_posters'),
        ),
    ]
