# Generated by Django 4.2.15 on 2024-08-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_movie_review_count_movie_synopsis_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
