# Generated by Django 4.2.15 on 2024-08-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='age',
            new_name='birth_year',
        ),
        migrations.AddField(
            model_name='director',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
