# Generated by Django 4.2.15 on 2024-08-20 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
