# Generated by Django 4.2.15 on 2024-08-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review_count',
        ),
    ]
