# Generated by Django 4.2.15 on 2024-08-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
